unit-config: &unit-config
  environment:
    COMPOSER_PREFER_LOWEST: 0
  steps:
    - checkout

    - run:
        name: Install latest composer
        command: |
          php -r "copy('https://raw.githubusercontent.com/composer/getcomposer.org/master/web/installer', 'composer-setup.php');"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          mv composer.phar /usr/local/bin/composer

    - run:
        name: Write COMPOSER_PREFER_LOWEST to file
        command: echo "$COMPOSER_PREFER_LOWEST" > ~/COMPOSER_PREFER_LOWEST.txt

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-composer-cache-{{ checksum "~/COMPOSER_PREFER_LOWEST.txt" }}-{{ checksum "composer.json" }}
        # Fall back to using the latest cache if no exact match is found.
        - v1-composer-cache-{{ checksum "~/COMPOSER_PREFER_LOWEST.txt" }}

    - run:
        name: Validate composer files
        command: composer validate --strict

    - run:
        name: Install PHP extensions
        command: |
            printf '\n' | sudo pecl install redis
            sudo docker-php-ext-enable redis

    - run:
        name: Install composer packages
        command: |
          if [ $COMPOSER_PREFER_LOWEST -eq "1" ]; then
            composer update --no-ansi --no-progress --optimize-autoloader --no-interaction --no-plugins --no-scripts --prefer-dist --prefer-stable --prefer-lowest
          else
            composer update --no-ansi --no-progress --optimize-autoloader --no-interaction --no-plugins --no-scripts --prefer-dist --prefer-stable
          fi

    - save_cache:
        key: v1-composer-cache-{{ checksum "~/COMPOSER_PREFER_LOWEST.txt" }}-{{ checksum "composer.json" }}
        paths:
          - ./vendor

    - run:
        name: Wait for backing services to start
        command: dockerize -wait tcp://127.0.0.1:6379 -timeout 30s

    - run:
        name: Run PHP Code Sniffer
        command: ./vendor/bin/phpcs

    - run:
        name: Run tests
        command: ./vendor/bin/phpunit

version: 2.1
jobs:
  php74:
    <<: *unit-config
    docker:
      - image: circleci/php:7.4-cli-node
      - image: circleci/redis:5-alpine
    environment:
      COMPOSER_PREFER_LOWEST: 0

  php74-lowest:
    <<: *unit-config
    docker:
      - image: circleci/php:7.4-cli-node
      - image: circleci/redis:5-alpine
    environment:
      COMPOSER_PREFER_LOWEST: 1

  php73:
    <<: *unit-config
    docker:
      - image: circleci/php:7.3-cli-node
      - image: circleci/redis:5-alpine
    environment:
      COMPOSER_PREFER_LOWEST: 0

  php73-lowest:
    <<: *unit-config
    docker:
      - image: circleci/php:7.3-cli-node
      - image: circleci/redis:5-alpine
    environment:
      COMPOSER_PREFER_LOWEST: 1

  php72:
    <<: *unit-config
    docker:
      - image: circleci/php:7.2-cli-node
      - image: circleci/redis:5-alpine
    environment:
      COMPOSER_PREFER_LOWEST: 0

  php72-lowest:
    <<: *unit-config
    docker:
      - image: circleci/php:7.2-cli-node
      - image: circleci/redis:5-alpine
    environment:
      COMPOSER_PREFER_LOWEST: 1

workflows:
  version: 2
  units:
    jobs:
      - php74
      - php74-lowest
      - php73
      - php73-lowest
      - php72
      - php72-lowest
